ft

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,13 +1,28 @@
 #!/usr/bin/env bash
-#+    The path to the file to be transferred.
-#+    The IP of the server to transfer the file to.
-#+    The username that scp connects with.
-#+    The path to the SSH private key that scp uses.
+# checking for command line arguments34 
 # By: Natnale Bimer
 
-if [ $# -lt 4 ]
+if [S#-1t 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
+
+# assigning paramentals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_shh_key=$4
+
+# disabbling strict host key checking
+
+scp -o "StrictHostKeychecking=no" -i "Spath_to_ssh_key" "Spath_to_file" "Susername@Sip:-/"
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "Transfer successful"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+	echo "Transfer Failed"
 fi
