not yet

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,28 +1,25 @@
 #!/usr/bin/env bash
-# checking for command line arguments34 
-# By: Natnale Bimer
-
-if [S#-1t 4 ]
+# Checking for command-line argument
+if [ $# -lt 4 ]
 then
-	echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-# assigning paramentals to variables
+# Assigning Arguments to variables
 
 path_to_file=$1
 ip=$2
 username=$3
-path_to_shh_key=$4
+path_to_ssh_key=$4
 
-# disabbling strict host key checking
 
-scp -o "StrictHostKeychecking=no" -i "Spath_to_ssh_key" "Spath_to_file" "Susername@Sip:-/"
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-# checking if the transfer was successful
+# Checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-	echo "Transfer successful"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "Transfer Failed"
-fi
+  echo "FILE TRANSFER FAILED"
